# shared env for all repro scripts
export HF_HOME=/cluster-storage/models HF_HUB_CACHE=/scratch/hf/hub
export HF_HUB_OFFLINE=${HF_HUB_OFFLINE:-1}
export MODEL=${MODEL:-openai/gpt-oss-120b}
export DRAFT=${DRAFT:-lmsys/EAGLE3-gpt-oss-120b-bf16}
export TP=${TP:-4}
export PREFILL_GPUS=${PREFILL_GPUS:-0,1,2,3}
export DECODE_GPUS=${DECODE_GPUS:-4,5,6,7}
export PREFILL_PORT=${PREFILL_PORT:-30100} DECODE_PORT=${DECODE_PORT:-30200} LB_PORT=${LB_PORT:-8000} BOOTSTRAP_PORT=${BOOTSTRAP_PORT:-8998}
export NCCL_P=${NCCL_P:-30300} NCCL_D=${NCCL_D:-30400}
export PREFILL_TP=${PREFILL_TP:-$TP} DECODE_TP=${DECODE_TP:-$TP}
export TRANSFER=${TRANSFER:-nixl}
export ATTN=${ATTN:-triton}
export SGLANG_ENABLE_UNIFIED_RADIX_TREE=1
export SGLANG_ALLOW_OVERWRITE_LONGER_CONTEXT_LEN=1
